In [ ]:
import pandas as pd
import glob

# Read all CSV files from the fire_info directory
csv_files = glob.glob('fire_info/*.csv')

# Initialize a list to store the filtered DataFrames
filtered_dfs = []

# Loop through each CSV file
for file in csv_files:
    # Read the CSV file into a DataFrame
    df = pd.read_csv(file)
    # Filter rows where confidence is 'h'
    filtered_df = df[df['confidence'] == 'h']
    # Append the filtered DataFrame to the list
    filtered_dfs.append(filtered_df)

# Concatenate all filtered DataFrames at once
filtered_data = pd.concat(filtered_dfs, ignore_index=True)

,latitude,longitude,brightness,scan,track,acq_date,acq_time,satellite,instrument,confidence,version,bright_t31,frp,daynight,type
0,68.41180,83.61930,367.0,0.54,0.68,2022-03-22,25,N,VIIRS,h,2,245.84,8.47,N,2
1,66.95627,75.53905,367.0,0.55,0.68,2022-03-22,26,N,VIIRS,h,2,262.21,108.90,N,2
2,58.84002,2.23684,367.0,0.71,0.75,2022-03-22,32,N,VIIRS,h,2,275.21,22.78,N,3
3,52.55544,39.61284,367.0,0.34,0.56,2022-03-22,32,N,VIIRS,h,2,274.41,2.75,N,2
4,28.11784,0.30673,367.0,0.34,0.56,2022-03-22,221,N,VIIRS,h,2,291.46,4.29,N,2

In [7]:
# Define the chunk size
chunk_size = 100000

# Loop through the DataFrame and save each chunk to a separate CSV file
for i in range(0, len(filtered_data), chunk_size):
    chunk = filtered_data.iloc[i:i + chunk_size]
    chunk.to_csv(f'filtered_data_chunk_{i // chunk_size}.csv', index=False)